### ISSUE TITLE
whlug.org 无法访问

### ISSUE THREAD

**Issue by felixonmars** [WHLUG/whlug.github.io#1]
好像解析到了 github pages，但是打开是 404 哦 :(

**Comment by tuhaihe** [comment]
@felixonmars 嗯，DNS 我已经设置成功。原因出在本地的文件没有生成成功。
欢迎使用 Jekyll 重新制作页面。如需要权限，我加你为管理员。

**Comment by felixonmars** [comment]
我还不熟悉 Jekyll 和 GitHub Pages，不过可以试一试 :)

**Comment by tuhaihe** [comment]
@felixonmars 这个非常简单，可以参考我之前写的一篇文章：http://tuhaihe.com/2014/07/09/use-jekyll-and-github-to-build-blog.html

还有很多 Jekyll theme 模板可供选择，选择一个做下定制即可: http://jekyllthemes.org/

上面的文案，你先写，写完告诉我，我再来改进~

**Comment by felixonmars** [comment]
按照帮助文档，我先补了一个 CNAME 文件进去，这样 whlug.org 打开是当前的静态文件了。
